[package]
name = "ratatui-counter-app"
version = "0.1.0"
authors = ["Dheepak Krishnamurthy <me@kdheepak.com>"]
license = "MIT"
edition = "2021"
publish.workspace = true

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = "0.26.1"
