[package]
name = "hello-ratatui"
version = "0.1.0"
authors = ["Josh McKinney <joshka@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
color-eyre = "0.6.4"
crossterm = "0.29.0"
ratatui = "0.29.0"
